- hosts: all
  remote_user: paulo_kinos
  become: yes
  tasks:
          - name: Ajustando o TimeZone do Servidor
            timezone:
                    name: America/Sao_Paulo
          
          - name: Instalando Apache
            apt:
                    name: apache2
                    state: present
          - name: enable service apache2
            systemd:
                    name: apache2
                    enabled: yes
                    masked: no
          - name: start apache2
            systemd:
                    state: started
                    name: apache2
